site_name: WEC-Grid
site_description: Integrating Wave Energy Converter Models into Power System Simulations
repo_url: https://github.com/acep/WEC-GRID
theme:
  name: ivory
  favicon: images/logo.png  # Browser tab icon
  logo: images/logo.png     # Main site logo
  nav_style: dark

plugins:
  - search
  # - plantuml:
  #     puml_url: https://www.plantuml.com/plantuml/
  #     num_workers: 8

  # Temporarily disabled due to AST parsing error
  # - mkapi:
  #     src_dirs: [src]
  #     filters: [
  #       "!^_",        # Exclude private methods
  #       "!^test_",    # Exclude test functions
  #     ]
  - mkdocs-jupyter:
      include: ["*.ipynb"] 
      execute: false
      include_source: True
  # Temporarily disabled to reduce warnings during initial setup
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         paths: [src]
  #         options:
  #           show_source: false
  #           docstring_style: google
  #           show_signature_annotations: false
  #           show_if_no_docstring: false
  #           filters: ["!^_"]
  #           ignore_init_summary: true
  #           merge_init_into_class: true
nav:
  - Getting Started:
      - Introduction: index.md
      - Software Design: software-design.md
      - Installation: install.md
      - Quick Start: quickstart.md
  - User Guide:
      - WECGrid Components:
          - Engine: user-guide/components/engine.md
          - Database: user-guide/components/database.md
          - Time: user-guide/components/time-manager.md
          - Power System Modelers: user-guide/components/modelers.md
          - PSS/E: user-guide/components/psse.md
          - PyPSA: user-guide/components/pypsa.md
          - WEC-Sim Runner: user-guide/components/wecsim.md
          - WEC Components: user-guide/components/wec.md
          - Plot: user-guide/components/plotting.md
      - Models:
          - Grid Models: user-guide/models/grid-models.md
          - WEC Models: user-guide/models/wec-models.md
  - Examples & Data:
      # - Basic Example: examples/basic-example.md
      - Example 1: examples/example1.ipynb
      - Example 2: examples/example2.ipynb
      - Example 3: examples/example3.ipynb
      - Example 4 : examples/example4.ipynb
      #- WEC-Sim: examples/wec-sim.ipynb
  - Reference:
      - API Reference: reference/api.md
      - Troubleshooting: reference/troubleshooting.md
      - Citation: reference/citation.md
